// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnUisHyvZqD6kkcSUch8L1I7N5HvRRqlE',
    appId: '1:1078256056098:web:f341f57384009c5330d77b',
    messagingSenderId: '1078256056098',
    projectId: 'plantifyeccomerceapp',
    authDomain: 'plantifyeccomerceapp.firebaseapp.com',
    storageBucket: 'plantifyeccomerceapp.appspot.com',
    measurementId: 'G-D60K305GCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkiydJKWBU2e1AxbxBoOQZRhURqnqLyQY',
    appId: '1:1078256056098:android:3fc00dd07b22f8e430d77b',
    messagingSenderId: '1078256056098',
    projectId: 'plantifyeccomerceapp',
    storageBucket: 'plantifyeccomerceapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpWEJkgPUywvs3-6127QNq0khG17PpDD8',
    appId: '1:1078256056098:ios:a8475f55cc438b5530d77b',
    messagingSenderId: '1078256056098',
    projectId: 'plantifyeccomerceapp',
    storageBucket: 'plantifyeccomerceapp.appspot.com',
    iosClientId: '1078256056098-cqfntpt73e48281gtg0fdkcifr265gjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantifyEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpWEJkgPUywvs3-6127QNq0khG17PpDD8',
    appId: '1:1078256056098:ios:a8475f55cc438b5530d77b',
    messagingSenderId: '1078256056098',
    projectId: 'plantifyeccomerceapp',
    storageBucket: 'plantifyeccomerceapp.appspot.com',
    iosClientId: '1078256056098-cqfntpt73e48281gtg0fdkcifr265gjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantifyEcommerceApp',
  );
}
